### ISSUE TITLE
$pv1volt falscher substring

### ISSUE THREAD

**Issue by rabsol** [riogrande75/infinipoll10k#2]
die Zeile 262 sollte so ausssehen:

 $pv1volt = (substr($antw[0],5,5)/10);

mit "4" ist der substring zu kurz

**Comment by riogrande75** [comment]
No, on all inverters in my service the value is only 4 digits long:
![grafik](https://github.com/user-attachments/assets/b5cc3072-b834-4cfa-a544-7d077bebfd33)
Also actual protocol description states this:
![grafik](https://github.com/user-attachments/assets/b89a2b51-965f-4e20-9a35-e0213b251d90)

Off course it could be that voltronic extended this in newer firmware versions. Then pls. adapt to your needs.

**Comment by riogrande75** [comment]
Issue closed as not reproducible.

**Comment by riogrande75** [comment]
Issue closed as not reproducible.
